### Numpy
Numpy is a fundamental library for scientific computing in python. It provides support for arrays and matrices, along with a collection of methematical functions to operate on these data structures. in this lesson, we will cover the basics of numpy, focusing on array and vectorized operation.

In [2]:
!pip install numpy

In [3]:
import numpy as np

#1D array
arr1 =np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr1.reshape(1,5) # 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [6]:
## 2D array
arr2  = np.array([[1,2,3,4,5],[6,7,8,9,0]])
arr2.shape

(2, 5)

In [7]:
arr3 = np.arange(0,10,2) ## 0 for starting point, 10 for ending, 2 for skip
arr3

array([0, 2, 4, 6, 8])

In [8]:
arr3.reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [9]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
## attribute of numpy
arr  = np.array([[1,2,3],[4,5,6]])

print("Array:\n", arr)
print("Shape:",arr.shape) # output: (2,3)
print("Number of dimensions:", arr.ndim) #output: 2
print("Size (number of elements): ", arr.size) #output:6
print("Data type:", arr.dtype) # output: int64 (may vary based on platfom)
print('Item size (in bytes): ', arr.itemsize) # output: 8 (may vary based on platform)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements):  6
Data type: int64
Item size (in bytes):  8


In [12]:
## Numpy Vectorized Operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,0])


## element wise addition
print("Addition:", arr1+arr2)

## Element wise Substraction
print("Substraction:", arr1-arr2)


## Element wise substraction
print("Multiplication: ", arr1*arr2)

## Element-wise multiplication
print("Division: ", arr1/arr2)

Addition: [ 7  9 11 13  5]
Substraction: [-5 -5 -5 -5  5]
Multiplication:  [ 6 14 24 36  0]
Division:  [0.16666667 0.28571429 0.375      0.44444444        inf]


C:\Users\Professor\AppData\Local\Temp\ipykernel_17544\1592447632.py:17: RuntimeWarning: divide by zero encountered in divide
  print("Division: ", arr1/arr2)


In [13]:
## Universal Functions
arr = np.array([2,4,6,8])

## square root
print(np.sqrt(arr))

## exponential
print(np.exp(arr))

## sin
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.41421356 2.         2.44948974 2.82842712]
[   7.3890561    54.59815003  403.42879349 2980.95798704]
[ 0.90929743 -0.7568025  -0.2794155   0.98935825]
[0.69314718 1.38629436 1.79175947 2.07944154]


In [17]:
## Array licing and Indexing
arr = np.array([[1,2,3,4,5],[6,7,8,9,0],[11,22,33,44,55]])
print("Array: \n", arr)


Array: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9  0]
 [11 22 33 44 55]]


In [18]:
arr[0]

array([1, 2, 3, 4, 5])

In [26]:
print(arr[1:,3:])

[[ 9  0]
 [44 55]]
