### Numpy
Numpy is a fundamental library for scientific computing in python. It provides support for arrays and matrices, along with a collection of methematical functions to operate on these data structures. in this lesson, we will cover the basics of numpy, focusing on array and vectorized operation.

In [1]:
!pip install numpy

In [ ]:
import numpy as np

#1D array
arr1 =np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [3]:
type(arr1)

numpy.ndarray

In [ ]:
arr1.reshape(1,5) # 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [ ]:
## 2D array
arr2  = np.array([[1,2,3,4,5],[6,7,8,9,0]])
arr2.shape

(2, 5)

In [ ]:
arr3 = np.arange(0,10,2) ## 0 for starting point, 10 for ending, 2 for skip
arr3

array([0, 2, 4, 6, 8])

In [ ]:
arr3.reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
## attribute of numpy
arr  = np.array([[1,2,3],[4,5,6]])

print("Array:\n", arr)
print("Shape:",arr.shape) # output: (2,3)
print("Number of dimensions:", arr.ndim) #output: 2
print("Size (number of elements): ", arr.size) #output:6
print("Data type:", arr.dtype) # output: int64 (may vary based on platfom)
print('Item size (in bytes): ', arr.itemsize) # output: 8 (may vary based on platform)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements):  6
Data type: int64
Item size (in bytes):  8


In [ ]:
## Numpy Vectorized Operation
